# Generated by Django 4.1.5 on 2023-03-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productPhoto',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
