# Generated by Django 4.1.5 on 2023-04-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_productphoto_productimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='Favorite',
        ),
    ]
