# Generated by Django 4.1.5 on 2023-03-27 13:38

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_prodcutdescription_product_productdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, null=True)),
                ('url', models.TextField()),
                ('method', models.CharField(max_length=255)),
                ('header', models.TextField()),
                ('parameter', models.TextField()),
                ('body', models.TextField()),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('response_code', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['-action_time'],
            },
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='product',
            name='preorderTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=auto_prefetch.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='api.product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='courierName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='courierPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='productPrice',
            field=models.BigIntegerField(default=0),
        ),
    ]
