# Generated by Django 4.1.5 on 2023-03-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0003_masterstatus_payment_paymentmethod_paymenttype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymentMethodId',
            new_name='paymentMethod',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymentTypeId',
            new_name='paymentType',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='transactionId',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categoryId',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sellerId',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='customerId',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='customerId',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sellerId',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='transactiondetail',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='transactiondetail',
            old_name='transactionId',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='transactionstatus',
            old_name='masterStatusId',
            new_name='masterStatus',
        ),
        migrations.RenameField(
            model_name='transactionstatus',
            old_name='transactionId',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='roleId',
            new_name='role',
        ),
        migrations.AddField(
            model_name='transactionstatus',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.CharField(max_length=255)),
                ('serialized_data', models.TextField()),
                ('object_repr', models.TextField()),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action', models.IntegerField(choices=[(0, 'CREATED'), (1, 'UPDATED'), (2, 'DELETED')])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-action_time'],
            },
        ),
    ]
