# Generated by Django 4.1.5 on 2023-04-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_favourite_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='is_deleted',
        ),
    ]
